source :rubygems

gem "eventmachine"
gem "em-http-request"
gem "uuidtools"
gem "sinatra"
gem "thin"
gem "json"
gem "datamapper", ">= 0.10.2"
gem "do_sqlite3"
gem "dm-sqlite-adapter"
gem "httpclient", :require => ['http-access2']
gem "nats"
gem "curb"

gem 'vcap_common', '~> 1.0.3', :require => ['vcap/common', 'vcap/component']
gem 'vcap_logging', '>=0.1.3', :require => ['vcap/logging']
gem 'vcap_services_base'

group :test do
  gem "rake"
  gem "rspec"
end
